### ISSUE TITLE
Long version name recognition error

### ISSUE THREAD

**Issue by Sun-ZhenXing** [filllabs/dependi#150]
**Describe the bug**

![image](https://github.com/user-attachments/assets/5d2a013d-dc78-47a8-bf9c-66fbd7570a5a)

**To Reproduce**

1. install `opencv-python` in a python proj

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windws [e.g. iOS]
 - Version 11 [e.g. 22]

**Additional context**

```log
Version: 1.93.1 (user setup)
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631
```

**Comment by kadirkaang** [comment]
Hi @Sun-ZhenXing,

Thanks for your patience while we look into this issue! Could you let us know if there’s a lock file for the manifest file related to it? If you have it, sharing would be super helpful!

Thanks!

**Comment by Sun-ZhenXing** [comment]
Sure. [bug-report.zip](https://github.com/user-attachments/files/17097154/bug-report.zip)

`pyproject.toml`:

```toml
[project]
name = "bug-report"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "opencv-python>=4.10.0.84",
]
```

You can also create your own, use `uv` to manage this Python project.

```bash
uv init bug-report
cd bug-report
uv venv
.venv\Scripts\activate
uv add opencv-python
code .
```
