### ISSUE TITLE
Autocomplete in Cargo.toml does not respect whitespace when completing object literal `{ }`

### ISSUE THREAD

**Issue by cpud36** [filllabs/dependi#155]
**Describe the bug**
When writing dependencies array a completion of `{ }` removes typed space:
```toml
# Here <|> represents the cursor
[dependencies]
foo = <|>
# type TAB transforms into:
foo ={ <|> }
#    ^---- no space here
#     ^--- probably extra space here
```

**To Reproduce**
1. Open Cargo.toml and put cursor on the line after [dependencies]
2. Type `foo = `
3. Wait until a completion shows the object literal `{ }` as a completion - accept it

**Expected behavior**
```toml
[dependencies]
foo = { <|> }
#    ^--------- space before is not deleted
#      ^---^--- space around is nice to have, but not strictly required
```

**Screenshots**
Before completion:
![Before completion](https://github.com/user-attachments/assets/2b38381b-5f51-47a8-88b3-e6e315c7e34a)
After completion:
![After completion](https://github.com/user-attachments/assets/badb3e86-8484-4cfa-bf23-7f83c2ab2682)

**Additional context**
I use it for workspace dependencies. The bug happens most of the time, but sometimes it does the right thing; do not know why.

Probably related problem, is the the completion of `workspace<TAB>` eats a space in front. I can provide futher details if needed.
