### ISSUE TITLE
Cargo.toml `packagename.features = [...]` isn't handled correctly

### ISSUE THREAD

**Issue by crumblingstatue** [filllabs/dependi#208]
```toml
[dependencies]
rfd.version = "0.15.1"
rfd.default-features = false
rfd.features = ["gtk3"]
```

The `rfd.features = ["gtk3"]` part returns ` Error: statusCode=404`

![image](https://github.com/user-attachments/assets/7b5bb060-4169-4ba9-b080-58e19b8c010b)
