### ISSUE TITLE
Wrong suggestions for entries with "extras"

### ISSUE THREAD

**Issue by alanwilter** [filllabs/dependi#217]
I have this in my `pyproject.toml`:

```toml
[tool.poetry.group.conversion.dependencies]
torch = { version = "^2.6.0+cpu", source = "pytorch-cpu" }
torchvision = { version = "^0.21.0+cpu", source = "pytorch-cpu" }
```

And Dependi 0.7.13 shows:

<img width="649" alt="Image" src="https://github.com/user-attachments/assets/21c3dadd-7d57-4345-a174-0993035976a2" />

which is not correct at all.
