### ISSUE TITLE
Support for GitHub Actions

### ISSUE THREAD

**Issue by per-oestergaard** [filllabs/dependi#239]
**Is your feature request related to a problem? Please describe.**
Dependi is great. However, it would be even greater, if it could also keep an eye on my GitHub action `use` statements. And ideally use the hash. Yes, I do know that Dependabot does this, but I want to be able to do it in my IDE and not have PRs as that is much easier.

**Describe the solution you'd like**

Update something like -
```yaml
runs:
  using: "example"
  steps:
    - uses: actions/checkout@v4
```
to
```
runs:
  using: "example"
  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
```
E.g. replace any version or hash reference to the latest version's commit hash including an explanatory version comment.
It should also warn if the source repo has been archived.

It should handle files in .github/actions as well as .github/workflows.

**Describe alternatives you've considered**
There might be another extension that I did not find.
I did not find a way to run Dependabot locally.

**Additional context**
Not that I can think of.
